name: Run URL Extraction Script

on:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install requests

      - name: Run script
        run: |
          python Si-Cert-Extract.py
      
      - name: Commit Output File
        run: |
          git config user.name "gasa46"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "crongenerated"
          git push
