name: Run URL Extraction Script

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install requests

      - name: Run script
        run: |
          python Si-Cert-Extract.py
      
      - name: Commit Output File
        run: |
          git config user.name "gasa46"
          git config user.email "gasa46@gmail.com"
          git add -A SI-CERT-last.txt
          git commit -m "Manual"
          git push
